// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseModal: typeof import('./components/BaseUse/BaseModal.md')['default']
    BaseUse: typeof import('./components/BaseUse/BaseUse.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElementModal: typeof import('./components/RealCase/ElementModal.vue')['default']
    ElementModalMd: typeof import('./components/RealCase/ElementModalMd.md')['default']
    ElementModalViewMd: typeof import('./components/RealCase/ElementModalViewMd.md')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Modal: typeof import('./components/Modal.vue')['default']
    PromiseModal: typeof import('./components/BaseUse/PromiseModal.md')['default']
    PromiseModalView: typeof import('./components/BaseUse/PromiseModalView.md')['default']
    README: typeof import('./components/README.md')['default']
    RealCase: typeof import('./components/RealCase/RealCase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagList: typeof import('./components/Tag/TagList.vue')['default']
    TagOption: typeof import('./components/Tag/TagOption.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    Usage: typeof import('./components/Usage/Usage.md')['default']
    UseModalView: typeof import('./components/BaseUse/UseModalView.md')['default']
  }
}
